//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChatApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatContent
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int SendBy { get; set; }
        public int SendTo { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime SendOn { get; set; }
    
        public virtual ChatSession ChatSession { get; set; }
    }
}
