//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChatApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatSessionJoinner
    {
        public int SessionId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> JoinedOn { get; set; }
        public Nullable<System.DateTime> LeftOn { get; set; }
        public Nullable<System.Guid> ConnectionID { get; set; }
        public int Id { get; set; }
    
        public virtual ChatSession ChatSession { get; set; }
        public virtual User User { get; set; }
    }
}
