//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChatApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChatSessions = new HashSet<ChatSession>();
            this.ChatSessionJoinners = new HashSet<ChatSessionJoinner>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserGender { get; set; }
        public bool UserIsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastLogOnDate { get; set; }
        public int UserType { get; set; }
        public bool UserIsOnLine { get; set; }
    
        public virtual ICollection<ChatSession> ChatSessions { get; set; }
        public virtual ICollection<ChatSessionJoinner> ChatSessionJoinners { get; set; }
    }
}
